---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rgravlin-github-com-v1-networktest
  failurePolicy: Fail
  name: mnetworktest.kb.io
  rules:
  - apiGroups:
    - rgravlin.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networktests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rgravlin-github-com-v1-networktest
  failurePolicy: Fail
  name: vnetworktest.kb.io
  rules:
  - apiGroups:
    - rgravlin.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networktests
  sideEffects: None
