name: test and build
on:
  push:
    branches-ignore:
      - main

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m

  build-runner:
    needs: [lint-go]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Filter for Runner changes
        uses: dorny/paths-filter@v3
        id: docker-changes
        with:
          filters: |
            src:
              - 'docker/**'

      - name: Setup Go
        if: steps.docker-changes.outputs.src == 'true'
        run: docker build docker/ -t ryangravlin/networkoperator-runner:latest

      - name: Set up QEMU
        if: steps.docker-changes.outputs.src == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.docker-changes.outputs.src == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: steps.docker-changes.outputs.src == 'true'
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ryangravlin/networktest-runner:branch

  build-operator:
    needs: [lint-go]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Filter for Golang project files
        uses: dorny/paths-filter@v3
        id: go-changes
        with:
          filters: |
            src:
              - 'cmd/**'
              - 'internal/**'
              - 'go.mod'
              - 'go.sum'
              - 'Dockerfile'

      - name: Setup Go
        if: steps.go-changes.outputs.src == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Test with the Go CLI
        if: steps.go-changes.outputs.src == 'true'
        run: make test

      - name: Build
        if: steps.go-changes.outputs.src == 'true'
        run: make

      - name: Set up QEMU
        if: steps.go-changes.outputs.src == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.go-changes.outputs.src == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: steps.go-changes.outputs.src == 'true'
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ryangravlin/networktest-operator:branch
