name: tag and release
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  tag-and-release:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: version-tag
        id: tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push controller
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ryangravlin/networktest-operator:latest,ryangravlin/networktest-operator:${{ steps.tag.outputs.new_tag }}

      - name: Build and push runner
        uses: docker/build-push-action@v6
        with:
          context: "docker/"
          push: true
          tags: ryangravlin/networktest-runner:latest,ryangravlin/networktest-runner:${{ steps.tag.outputs.new_tag }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}